In [2]:
import numpy as np

## Boolean Indexing
The boolean array must be of the same length as the array axis it's indexing

In [4]:
names = np.array(['Bose','Joshi','Ganesh','Bose','Ganesh','Joshi','Joshi'])
data = np.random.randn(7,4)
print(names,'\n',data)

['Bose' 'Joshi' 'Ganesh' 'Bose' 'Ganesh' 'Joshi' 'Joshi'] 
 [[-1.05757032 -0.90016292 -0.60692535 -0.7648878 ]
 [ 0.53553959  1.39628404 -0.20837839 -0.03729687]
 [-0.65606994  0.13442554  0.02519102 -0.45224945]
 [ 1.03734118  0.19072753  1.1942137   0.92087415]
 [-1.03975733  0.19113409  0.84945205  0.90923434]
 [ 1.6916658  -0.67942897 -1.53713194  2.66073854]
 [ 0.63622557 -1.06601746 -1.61951474  1.90777828]]


In [5]:
names

array(['Bose', 'Joshi', 'Ganesh', 'Bose', 'Ganesh', 'Joshi', 'Joshi'],
      dtype='<U6')

In [6]:
data

array([[-1.05757032, -0.90016292, -0.60692535, -0.7648878 ],
       [ 0.53553959,  1.39628404, -0.20837839, -0.03729687],
       [-0.65606994,  0.13442554,  0.02519102, -0.45224945],
       [ 1.03734118,  0.19072753,  1.1942137 ,  0.92087415],
       [-1.03975733,  0.19113409,  0.84945205,  0.90923434],
       [ 1.6916658 , -0.67942897, -1.53713194,  2.66073854],
       [ 0.63622557, -1.06601746, -1.61951474,  1.90777828]])

In [9]:
data2 = np.array([5,10,15,20,25,26,27])
data2[names=='Bose']

array([ 5, 20])

In [10]:
data[names=='Joshi']

array([[ 0.53553959,  1.39628404, -0.20837839, -0.03729687],
       [ 1.6916658 , -0.67942897, -1.53713194,  2.66073854],
       [ 0.63622557, -1.06601746, -1.61951474,  1.90777828]])

In [13]:
data[names=='Bose']

array([[-1.05757032, -0.90016292, -0.60692535, -0.7648878 ],
       [ 1.03734118,  0.19072753,  1.1942137 ,  0.92087415]])

In [14]:
data[names=='Bose',2]

array([-0.60692535,  1.1942137 ])

In [15]:
data[names=='Bose',:2]

array([[-1.05757032, -0.90016292],
       [ 1.03734118,  0.19072753]])

In [38]:
print(names,'\n',data)

['Bose' 'Joshi' 'Ganesh' 'Bose' 'Ganesh' 'Joshi' 'Joshi'] 
 [[-1.30102608  0.94729484  0.20514641 -0.05025422]
 [-0.23057675  0.4068477   0.11570431 -0.3642778 ]
 [-0.62904896 -1.41361646 -0.10510566 -1.23376807]
 [-0.34040486 -0.92633539 -1.52004077 -0.37819485]
 [-0.71603914  2.0527056  -0.23084067 -0.98877823]
 [ 1.13305994 -0.3878861   0.0824793  -0.13176941]
 [ 0.6311587  -0.41872994  0.20940242  1.46136301]]


In [16]:
# select everthing except Bose
data[names!='Bose']

array([[ 0.53553959,  1.39628404, -0.20837839, -0.03729687],
       [-0.65606994,  0.13442554,  0.02519102, -0.45224945],
       [-1.03975733,  0.19113409,  0.84945205,  0.90923434],
       [ 1.6916658 , -0.67942897, -1.53713194,  2.66073854],
       [ 0.63622557, -1.06601746, -1.61951474,  1.90777828]])

In [17]:
data[names!='Bose',2:]

array([[-0.20837839, -0.03729687],
       [ 0.02519102, -0.45224945],
       [ 0.84945205,  0.90923434],
       [-1.53713194,  2.66073854],
       [-1.61951474,  1.90777828]])

In [19]:
# ~ operator to invert condition
# through variables
condition = names=='Bose'
print(data[~condition])
data[~(names=='Bose')]

[[ 0.53553959  1.39628404 -0.20837839 -0.03729687]
 [-0.65606994  0.13442554  0.02519102 -0.45224945]
 [-1.03975733  0.19113409  0.84945205  0.90923434]
 [ 1.6916658  -0.67942897 -1.53713194  2.66073854]
 [ 0.63622557 -1.06601746 -1.61951474  1.90777828]]


array([[ 0.53553959,  1.39628404, -0.20837839, -0.03729687],
       [-0.65606994,  0.13442554,  0.02519102, -0.45224945],
       [-1.03975733,  0.19113409,  0.84945205,  0.90923434],
       [ 1.6916658 , -0.67942897, -1.53713194,  2.66073854],
       [ 0.63622557, -1.06601746, -1.61951474,  1.90777828]])

In [20]:
# Use &(and) ,pipe operator for or condition. and , or does not work in boolean indexing
m1 = (names=='Bose') | (names=='Joshi')
data[m1]

array([[-1.05757032, -0.90016292, -0.60692535, -0.7648878 ],
       [ 0.53553959,  1.39628404, -0.20837839, -0.03729687],
       [ 1.03734118,  0.19072753,  1.1942137 ,  0.92087415],
       [ 1.6916658 , -0.67942897, -1.53713194,  2.66073854],
       [ 0.63622557, -1.06601746, -1.61951474,  1.90777828]])

In [21]:
m2 = (names=='Bose') & (len(names)>2)
data[m2]


array([[-1.05757032, -0.90016292, -0.60692535, -0.7648878 ],
       [ 1.03734118,  0.19072753,  1.1942137 ,  0.92087415]])

In [22]:
data[data<0]

array([-1.05757032, -0.90016292, -0.60692535, -0.7648878 , -0.20837839,
       -0.03729687, -0.65606994, -0.45224945, -1.03975733, -0.67942897,
       -1.53713194, -1.06601746, -1.61951474])

In [23]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.53553959, 1.39628404, 0.        , 0.        ],
       [0.        , 0.13442554, 0.02519102, 0.        ],
       [1.03734118, 0.19072753, 1.1942137 , 0.92087415],
       [0.        , 0.19113409, 0.84945205, 0.90923434],
       [1.6916658 , 0.        , 0.        , 2.66073854],
       [0.63622557, 0.        , 0.        , 1.90777828]])

In [24]:
data[names!='Joshi'] =6
data


array([[6.        , 6.        , 6.        , 6.        ],
       [0.53553959, 1.39628404, 0.        , 0.        ],
       [6.        , 6.        , 6.        , 6.        ],
       [6.        , 6.        , 6.        , 6.        ],
       [6.        , 6.        , 6.        , 6.        ],
       [1.6916658 , 0.        , 0.        , 2.66073854],
       [0.63622557, 0.        , 0.        , 1.90777828]])

## Fancy Indexing
indexing with integer values

In [25]:
arr = np.empty((8,4))
arr

array([[1.13012246e-311, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000],
       [3.87816845e-116, 5.02034658e+175, 1.29201298e+161,
        1.53458686e-075],
       [1.47791515e-075, 4.03333146e+175, 3.34584250e-033,
        7.75205681e-144],
       [3.59751658e+252, 1.46901661e+179, 3.75505006e+199,
        2.59027921e-144],
       [3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143],
       [8.00874991e+165, 9.28165459e-072, 1.74171408e+184,
        1.70322986e-051],
       [2.59027905e-144, 2.59903818e-144, 6.80774355e-091,
        1.83323181e-076],
       [3.85716144e-057, 1.11475752e+261, 1.16318408e-028,
        2.97707521e+296]])

In [26]:
# traditional ways
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [27]:
arr[[2,3,4]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [28]:
arr[[4,6,7,2]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [39]:
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[11,12,13,14]])
arr1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [40]:
arr1[[1,2]]

array([[ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [57]:
arr1[[-1,-2]]

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10]])

In [41]:
arr[[-4,-7,-2]]

array([[4., 4., 4., 4.],
       [1., 1., 1., 1.],
       [6., 6., 6., 6.]])

In [38]:
# reshape method
arr2 = np.random.rand(9,4)
arr2[[2,3,4]]

array([[0.41855457, 0.22691359, 0.07737371, 0.45965197],
       [0.65486474, 0.49505426, 0.98994671, 0.32196057],
       [0.93680805, 0.09267255, 0.54912906, 0.9025616 ]])

In [65]:
arr2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
# If you pass multiple index, selects 1-dimensional array of elements corresponding to each tuple of indices. 
arr2 = np.arange(32).reshape(8,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [55]:
print(arr2[[1,2,3]])
arr2[[1,2,3],[0,1,3]] # it takes in pair (1,0),(2,1),(3,3)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 4,  9, 15])

In [57]:
arr2[1:3,3] # general indexing and slicing can't give different value, it includes either individual or range.

array([ 7, 11])

In [74]:
arr2[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [75]:
arr2[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing arrays and swapping axes

In [58]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
# for 2 dimensional matrix , just we need to do arr.T . 
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [60]:
arr1 =  np.arange(16).reshape(2,2,4)
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
print(arr1.shape,arr1.T.shape)
# Usually , in transpose of matrix, sequence changes , (3,5).T => (5,3). In the same way (2,2,4).T => (4,2,2).
arr1.T

(2, 2, 4) (4, 2, 2)


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [64]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### clarification

In [69]:
arr1.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [63]:
arr1.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
# Axes should be reordered with second axis first, the first axis second, last axis unchanged

In [95]:
arr4 = np.arange(45).reshape(3,5,3)
arr4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [96]:
arr4_t = arr4.transpose(1,0,2)
arr4_t.shape

(5, 3, 3)

In [103]:
np.transpose(arr4,(1,0,2))

array([[[ 0,  1,  2],
        [15, 16, 17],
        [30, 31, 32]],

       [[ 3,  4,  5],
        [18, 19, 20],
        [33, 34, 35]],

       [[ 6,  7,  8],
        [21, 22, 23],
        [36, 37, 38]],

       [[ 9, 10, 11],
        [24, 25, 26],
        [39, 40, 41]],

       [[12, 13, 14],
        [27, 28, 29],
        [42, 43, 44]]])

In [97]:
arr4_t

array([[[ 0,  1,  2],
        [15, 16, 17],
        [30, 31, 32]],

       [[ 3,  4,  5],
        [18, 19, 20],
        [33, 34, 35]],

       [[ 6,  7,  8],
        [21, 22, 23],
        [36, 37, 38]],

       [[ 9, 10, 11],
        [24, 25, 26],
        [39, 40, 41]],

       [[12, 13, 14],
        [27, 28, 29],
        [42, 43, 44]]])

In [100]:
print(arr1.shape)
arr1

(2, 2, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
arr1.swapaxes(1,2) # => 2,4,2

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### clarification end

## Universal functions
The function that performs element-wise operations on data in ndarrays

In [70]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
print(f"sqrt: {np.sqrt(arr)}, sum: {np.sum(arr)} , max: {np.max(arr)}, min: {np.min(arr)}")
print(f"exp:{np.exp(arr)}")

sqrt: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ], sum: 45 , max: 9, min: 0
exp:[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [71]:
## Unary universal function which takes only 1 argument
# to find square root for all element in numpy array
arr_sqrt = np.sqrt(arr)
arr_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [105]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [107]:
np.ceil(arr_sqrt)

array([ 0.,  1.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.])

In [108]:
np.floor(arr_sqrt)

array([ 0.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  3.])

In [74]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x,'\n',y)

[ 0.28485604 -0.56426035 -0.2363572   0.98899645 -1.04749953  0.76453014
  1.2095053  -1.36389675] 
 [ 1.06745675  1.02388421  0.83988006 -0.10018955  0.08870237 -0.81071049
 -0.51072471  0.64503779]


## Binary universal function

In [75]:
np.maximum(x,y)

array([1.06745675, 1.02388421, 0.83988006, 0.98899645, 0.08870237,
       0.76453014, 1.2095053 , 0.64503779])

In [76]:
np.minimum(x,y)

array([ 0.28485604, -0.56426035, -0.2363572 , -0.10018955, -1.04749953,
       -0.81071049, -0.51072471, -1.36389675])

In [77]:
arr =  np.random.randn(7) * 10
arr

array([-9.73686688, 12.42571279, -8.43112442, 13.8720387 , -6.19240553,
       -1.6404089 ,  0.25226124])

In [78]:
remainder, whole = np.modf(arr)
print("remainder : ",remainder,'\n','whole part : ',whole)

remainder :  [-0.73686688  0.42571279 -0.43112442  0.8720387  -0.19240553 -0.6404089
  0.25226124] 
 whole part :  [-9. 12. -8. 13. -6. -1.  0.]


In [79]:
np.add(x,y)

array([ 1.35231279,  0.45962386,  0.60352286,  0.8888069 , -0.95879716,
       -0.04618035,  0.6987806 , -0.71885896])

In [80]:
np.subtract(x,y)

array([-0.78260071, -1.58814456, -1.07623726,  1.08918601, -1.1362019 ,
        1.57524063,  1.72023001, -2.00893455])

In [81]:
np.multiply(x,y)

array([ 0.3040715 , -0.57773726, -0.1985117 , -0.09908711, -0.09291569,
       -0.6198126 , -0.61772424, -0.87976495])

In [82]:
np.power(x,y) # =>  x^y

C:\Users\rahul\AppData\Local\Temp\ipykernel_19176\4088464382.py:1: RuntimeWarning: invalid value encountered in power
  np.power(x,y) # =>  x^y


array([0.26171959,        nan,        nan, 1.00110917,        nan,
       1.24317771, 0.9074238 ,        nan])

In [83]:
np.mod(x,y) # remainder of division x/y

array([ 0.28485604,  0.45962386,  0.60352286, -0.01289908,  0.01692886,
       -0.04618035, -0.32266881,  0.57121663])

In [84]:
print(x,'\n',y)

[ 0.28485604 -0.56426035 -0.2363572   0.98899645 -1.04749953  0.76453014
  1.2095053  -1.36389675] 
 [ 1.06745675  1.02388421  0.83988006 -0.10018955  0.08870237 -0.81071049
 -0.51072471  0.64503779]


In [85]:
np.mod(5,2)

1

In [86]:
np.greater(x,y)

array([False, False, False,  True, False,  True,  True, False])

In [88]:
np.where(x<y,x,y)

array([ 0.28485604, -0.56426035, -0.2363572 , -0.10018955, -1.04749953,
       -0.81071049, -0.51072471, -1.36389675])

In [90]:
np.isnan(arr)
np.square(arr)


array([9.48065766e+01, 1.54398338e+02, 7.10838590e+01, 1.92433458e+02,
       3.83458863e+01, 2.69094136e+00, 6.36357343e-02])

## conditional logics as array operations

In [91]:
arr = np.random.randn(4,4)
arr

array([[ 4.74817031e-01, -1.41927421e+00,  1.11978487e+00,
         4.76280563e-01],
       [-1.77684956e-01,  8.33852756e-04, -1.20756357e+00,
        -5.23641053e-01],
       [-7.52399470e-01,  6.06847472e-01, -1.18760950e+00,
        -7.57018080e-01],
       [ 2.49901514e+00, -8.78264443e-01, -2.05100716e-01,
        -3.11084783e-01]])

In [92]:
arr>0

array([[ True, False,  True,  True],
       [False,  True, False, False],
       [False,  True, False, False],
       [ True, False, False, False]])

In [94]:
# np. where(condition,value, else)
np.where(arr>0,2,-1)


array([[ 2, -1,  2,  2],
       [-1,  2, -1, -1],
       [-1,  2, -1, -1],
       [ 2, -1, -1, -1]])

In [95]:
np.where(arr<0,0,arr) # relu function will explained in deep learning

array([[4.74817031e-01, 0.00000000e+00, 1.11978487e+00, 4.76280563e-01],
       [0.00000000e+00, 8.33852756e-04, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.06847472e-01, 0.00000000e+00, 0.00000000e+00],
       [2.49901514e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [132]:
arr

array([[-0.32356624, -0.00794865, -1.81251067, -1.3351493 ],
       [-2.42780389,  0.28014023,  1.2144177 ,  1.31346978],
       [-0.86514802,  0.25471451, -0.76397267, -1.32938476],
       [ 0.51373705,  1.25708556, -0.21779154,  0.28732043]])

In [133]:
np.where(arr>0,3,arr)

array([[-0.32356624, -0.00794865, -1.81251067, -1.3351493 ],
       [-2.42780389,  3.        ,  3.        ,  3.        ],
       [-0.86514802,  3.        , -0.76397267, -1.32938476],
       [ 3.        ,  3.        , -0.21779154,  3.        ]])

## Mathematical and Statistical methods on numpy array

In [3]:
arr = np.random.randn(5,4)
arr

array([[ 1.62226261,  2.06754324, -0.40497075,  1.37014114],
       [ 0.27464774,  0.4877619 ,  0.55098103, -1.44569072],
       [ 0.09151303, -1.27459436,  0.53578212,  0.48921039],
       [-0.42192618, -0.32802023, -0.03944343, -1.1435114 ],
       [-1.02225753, -0.94859647, -0.56016949,  0.36143742]])

In [100]:
arr = np.array([[1,2,3],[2,4,6]])

In [101]:
# you can do in 2 ways 1) directly on array instance method 2) using numpy function
np.mean(arr) # i recommend it.

3.0

In [102]:
arr.mean()

3.0

In [103]:
arr.sum()

18

In [108]:
print(arr) # you can add arr as an whole or can do it axis wise also
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[1 2 3]
 [2 4 6]]
18
[3 6 9]
[ 6 12]


In [111]:
arr2 = [1,2,2,3,4,6]
np.median(arr)

2.5

In [112]:
# array instance method does not have direct median() method
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [114]:
print(np.min(arr),np.max(arr),np.argmin(arr),np.argmax(arr),np.std(arr),np.var(arr),np.cumsum(arr),np.cumprod(arr))

1 6 0 5 1.632993161855452 2.6666666666666665 [ 1  3  6  8 12 18] [  1   2   6  12  48 288]


In [12]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1.reshape(3,-1)
arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1 = arr1.reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr1.sum()

45

In [20]:
arr1.sum(axis = 0)

array([12, 15, 18])

In [23]:
arr1.sum(0)

array([12, 15, 18])

In [21]:
arr1.sum(axis=1)

array([ 6, 15, 24])

In [24]:
arr1.sum(1)

array([ 6, 15, 24])

In [22]:
arr.sum(axis=0)

array([ 0.54423966,  0.00409407,  0.08217947, -0.36841317])

In [15]:
arr.sum(axis=1)

array([ 3, 12, 21])

In [25]:
arr1.mean()

5.0

In [27]:
arr1.mean(0)

array([ 4.,  5.,  6.])

In [28]:
arr1.mean(1)

array([ 2.,  5.,  8.])

In [29]:
arr.mean(1) # => arr.mean(axis=1)

array([ 1.16374406, -0.03307501, -0.03952221, -0.48322531, -0.54239652])

In [30]:
arr.mean(0)

array([ 0.10884793,  0.00081881,  0.01643589, -0.07368263])

In [32]:
print("array : ",arr,'\n','array1 : ' , arr1)


array :  [[ 1.62226261  2.06754324 -0.40497075  1.37014114]
 [ 0.27464774  0.4877619   0.55098103 -1.44569072]
 [ 0.09151303 -1.27459436  0.53578212  0.48921039]
 [-0.42192618 -0.32802023 -0.03944343 -1.1435114 ]
 [-1.02225753 -0.94859647 -0.56016949  0.36143742]] 
 array1 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
arr1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [38]:
arr1.cumsum(0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [39]:
arr1.cumsum(1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [40]:
arr.cumsum()

array([ 1.62226261,  3.68980584,  3.28483509,  4.65497623,  4.92962396,
        5.41738587,  5.9683669 ,  4.52267618,  4.61418921,  3.33959485,
        3.87537697,  4.36458736,  3.94266118,  3.61464095,  3.57519752,
        2.43168612,  1.40942859,  0.46083211, -0.09933738,  0.26210004])

In [41]:
arr.cumsum(0)

array([[ 1.62226261,  2.06754324, -0.40497075,  1.37014114],
       [ 1.89691034,  2.55530514,  0.14601028, -0.07554958],
       [ 1.98842337,  1.28071078,  0.6817924 ,  0.41366081],
       [ 1.56649719,  0.95269054,  0.64234897, -0.72985058],
       [ 0.54423966,  0.00409407,  0.08217947, -0.36841317]])

In [42]:
arr.cumsum(1)

array([[ 1.62226261,  3.68980584,  3.28483509,  4.65497623],
       [ 0.27464774,  0.76240964,  1.31339067, -0.13230004],
       [ 0.09151303, -1.18308133, -0.64729922, -0.15808882],
       [-0.42192618, -0.74994641, -0.78938984, -1.93290124],
       [-1.02225753, -1.97085401, -2.5310235 , -2.16958608]])

In [43]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr1.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [45]:
arr1.cumprod(0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]], dtype=int32)

In [46]:
arr1.cumprod(1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [47]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr1.mean()

5.0

In [ ]:
# variance , mean = 5, sum = 45, (4,3,2,1,0,1,2,3,4) = 16+9+4+1+0+1+4+9+16 = 60/9 = 6.6

In [52]:
np.sqrt(6.6)

2.5690465157330258

In [50]:
arr1.std()

2.5819888974716112

In [51]:
arr1.std(0) # 4,5,6  = 9+0+9 = 6

array([ 2.44948974,  2.44948974,  2.44948974])

In [53]:
np.sqrt(6)

2.4494897427831779

In [54]:
arr1.var()

6.666666666666667

In [55]:
np.var(arr)

0.88973447006058937

In [56]:
arr1.max()

9

In [57]:
arr1.min()

1

In [58]:
# the position of minimum value in array
arr1.argmin()

0

In [59]:
# the position of maximum value in array
arr1.argmax()

8

In [60]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr1.sum()

45

In [62]:
arr1[arr1>2].sum()

42

In [63]:
arr1[arr1>3].min()

4

In [64]:
arr1[arr1<3].max()

2

In [66]:
(arr1>0).sum() ## Number of positive values

9

In [68]:
(arr1<4).sum() # Number of elements less than 4

3

In [69]:
arr1.any() # checks if any value is true

True

In [70]:
arr1.all() #  checks if all  values are true

True

In [73]:
arr

array([[ 1.62226261,  2.06754324, -0.40497075,  1.37014114],
       [ 0.27464774,  0.4877619 ,  0.55098103, -1.44569072],
       [ 0.09151303, -1.27459436,  0.53578212,  0.48921039],
       [-0.42192618, -0.32802023, -0.03944343, -1.1435114 ],
       [-1.02225753, -0.94859647, -0.56016949,  0.36143742]])

In [75]:
arr.all()

True

In [77]:
np.all([-2,2,3])
np.all([True, False ,True])

False

In [80]:
np.all([0,1,2]) # 0 - false, other than 0 true

False

## Sorting
sort() - Numpy array can be sorted in place with the sort method. 

In [81]:
arr = np.random.randn(6)
arr

array([  8.14434944e-01,   6.19852461e-02,  -1.97480115e-01,
         1.69879924e+00,  -8.50129170e-01,  -1.02264425e-03])

arr.sort(axis=-1, kind='quicksort', order=None)
kind = {'quicksort','mergesort','heapsort'}
order =  which field to compare first, second etc

#it does inplace and does not return any value

In [82]:
arr

array([  8.14434944e-01,   6.19852461e-02,  -1.97480115e-01,
         1.69879924e+00,  -8.50129170e-01,  -1.02264425e-03])

In [83]:
arr.sort()
arr

array([ -8.50129170e-01,  -1.97480115e-01,  -1.02264425e-03,
         6.19852461e-02,   8.14434944e-01,   1.69879924e+00])

In [85]:
arr1 = arr.sort()
arr1

In [86]:
arr1 = np.random.randn(3,3)
arr1

array([[ 0.58768506, -0.32334938,  0.10616885],
       [ 0.46128801, -0.15772214, -1.07821341],
       [-0.77753879, -0.37725463, -0.0202171 ]])

In [87]:
arr1.sort(1)
arr1

array([[-0.32334938,  0.10616885,  0.58768506],
       [-1.07821341, -0.15772214,  0.46128801],
       [-0.77753879, -0.37725463, -0.0202171 ]])

In [89]:
arr1.sort(0)
arr1

array([[-1.07821341, -0.37725463, -0.0202171 ],
       [-0.77753879, -0.15772214,  0.46128801],
       [-0.32334938,  0.10616885,  0.58768506]])

In [91]:
bigger_arr = np.random.randn(1000)
bigger_arr.sort()
# 5% quantile
bigger_arr[int(0.05*len(bigger_arr))]

-1.6300135321555085

In [94]:
# np.sort(bigger_arr) : returns copy , does not sort in place
arr2 =  np.random.randn(3,3)
print(arr2)
print(np.sort(arr2))
arr2


[[ 1.41048716 -1.57145943  1.00773862]
 [ 0.72039839  1.012489   -0.29443593]
 [ 1.77516319 -0.13123113  1.59547399]]
[[-1.57145943  1.00773862  1.41048716]
 [-0.29443593  0.72039839  1.012489  ]
 [-0.13123113  1.59547399  1.77516319]]


array([[ 1.41048716, -1.57145943,  1.00773862],
       [ 0.72039839,  1.012489  , -0.29443593],
       [ 1.77516319, -0.13123113,  1.59547399]])

## Unique and other set logic

In [95]:
names = np.array(['Bose','Joshi','Ganesh','Bose','Ganesh','Joshi','Joshi'])
names

array(['Bose', 'Joshi', 'Ganesh', 'Bose', 'Ganesh', 'Joshi', 'Joshi'], 
      dtype='<U6')

In [96]:
set(names)

{'Bose', 'Ganesh', 'Joshi'}

In [97]:
np.unique(names) # returns unique and sorted values # No array instance method ## important method

array(['Bose', 'Ganesh', 'Joshi'], 
      dtype='<U6')

In [98]:
sorted(set(names))

['Bose', 'Ganesh', 'Joshi']

In [99]:
# in1d checks the subarray is present in parent array or not
values = np.array([1,2,3,4,5,6])
np.in1d(values,[2,3,6])

array([False,  True,  True, False, False,  True], dtype=bool)

In [100]:
np.intersect1d(values,[1,2,9])

array([1, 2])

In [101]:
np.union1d(values,[1,2,9,3,12])

array([ 1,  2,  3,  4,  5,  6,  9, 12])

In [102]:
print(values)
np.setdiff1d(values,[1,2,9,3])

[1 2 3 4 5 6]


array([4, 5, 6])

In [103]:
np.setxor1d(values,[1,2,3,9])

array([4, 5, 6, 9])

In [2]:
import numpy as np
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('training_arr3',arr3) # .npy will get suffix as file name if you don't specify
np.save('training_arr3.npy',arr3)

In [4]:
np.load('training_arr3.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.save('name_array.npy',names)
np.save('name_array',names) # .npy is automatically appended in file extension

In [76]:
np.load('name_array.npy')

array(['Bose', 'Joshi', 'Ganesh', 'Bose', 'Ganesh', 'Joshi', 'Joshi'], 
      dtype='<U6')

In [5]:
np.savez('arr3_archive.npz',a=arr3,b=arr3)

In [6]:
archive =  np.load('arr3_archive.npz') # it return as a dictionary object
archive

In [7]:
print(archive['b'])
archive['a']

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
dict(archive)

{'a': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'b': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])}

In [9]:
arr2 = np.arange(20).reshape(5,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
np.savez('arr2_archive.npz',a=arr3,b=arr2)

In [14]:
np.load('arr2_archive.npz')['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.load('arr2_archive.npz')['b']

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Linear Algebra
#### Matrix Multiplication
#### Decompositions
#### Determinants
#### Square matrix mathematics

In [24]:
A = np.array([[2,0],[1,9]],dtype='int32')
B = np.array([[3,9],[4,7]],dtype='int32')
print(A, B)
print(np.dot(A,B))
print(A.dot(B))
A@B

[[2 0]
 [1 9]] [[3 9]
 [4 7]]
[[ 6 18]
 [39 72]]
[[ 6 18]
 [39 72]]


array([[ 6, 18],
       [39, 72]])

In [20]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[3,4],[5,6]])
print(x,'\n',y)

[[1 2 3]
 [4 5 6]] 
 [[1 2]
 [3 4]
 [5 6]]


In [21]:
# Matrix Multiplication:2X3,3X2 => 2X2 matrix
x.dot(y)

array([[22, 28],
       [49, 64]])

In [126]:
# Matrix multiplication : 3X2 ,2X3 => 3X3 matrix
y.dot(x)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [22]:
np.dot(x,y)

array([[22, 28],
       [49, 64]])

In [128]:
np.dot(y,x)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [25]:
x@y # matrix multiplication through infix operator , from python 3.5 onwards

array([[22, 28],
       [49, 64]])

In [27]:
y@x

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [32]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
print("x : ",x,'\n',"Ones matrix : ",np.ones(3))
x.dot(np.ones(3))

x :  [[1 2 3]
 [4 5 6]] 
 Ones matrix :  [1. 1. 1.]


array([ 6., 15.])

In [35]:
x.dot(np.ones(shape=(3,3)))

array([[ 6.,  6.,  6.],
       [15., 15., 15.]])

In [36]:
x@np.identity(3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [133]:
x@np.ones(3)

array([  6.,  15.])

##### numpy.linalg -> standard linear algebra library in python  whereas the same is performed in other languages like MATLAB and R using BLAS, LAPACK, MKL(math kernel library)

In [38]:
from numpy.linalg import inv, qr

In [40]:
A = np.array([[2,3,4],[-3,-3,-2],[-2,1,-1]])
print(A)
inv(A)

[[ 2  3  4]
 [-3 -3 -2]
 [-2  1 -1]]


array([[-0.2173913 , -0.30434783, -0.26086957],
       [-0.04347826, -0.26086957,  0.34782609],
       [ 0.39130435,  0.34782609, -0.13043478]])

In [41]:
x = np.random.randn(5,5)
x

array([[-0.66181921,  0.43854075,  0.62889809, -0.21938738,  0.76642612],
       [-0.68427792, -0.8817031 ,  0.14614788,  0.20971889,  0.55323738],
       [ 1.11028912, -0.163361  ,  0.14551522, -0.19461608, -1.5604064 ],
       [ 0.16922626, -0.82948312, -0.62954809, -1.22244965,  0.05399093],
       [-0.5158755 ,  0.89238977,  0.79247568,  1.28513909, -1.52394876]])

In [42]:
mat = x.T.dot(x)
mat

array([[ 2.43374795, -0.46901501, -0.8700135 , -1.08423368, -1.82300139],
       [-0.46901501,  2.4808069 ,  1.35256359,  1.91151889, -1.30151333],
       [-0.8700135 ,  1.35256359,  1.46239518,  1.65239037, -0.9058867 ],
       [-1.08423368,  1.91151889,  1.65239037,  3.27595387, -1.77292703],
       [-1.82300139, -1.30151333, -0.9058867 , -1.77292703,  5.65368358]])

In [43]:
inv(mat)

array([[ 1.61749878, -0.33400604,  1.05233143,  0.63994504,  0.8139575 ],
       [-0.33400604,  0.96889774, -0.77212846, -0.35043888, -0.11826336],
       [ 1.05233143, -0.77212846,  2.6167776 , -0.24897683,  0.50277884],
       [ 0.63994504, -0.35043888, -0.24897683,  1.07618587,  0.42325928],
       [ 0.8139575 , -0.11826336,  0.50277884,  0.42325928,  0.6253963 ]])

In [44]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.14484584e-16,  5.68356870e-16,
         5.83878599e-17,  4.79562917e-16],
       [ 2.15737339e-16,  1.00000000e+00,  1.29960564e-16,
        -2.39175107e-16,  2.32607451e-17],
       [-8.53363638e-16,  4.41271309e-16,  1.00000000e+00,
        -4.75994137e-16, -3.59154091e-16],
       [ 1.83076957e-16, -5.73738609e-17,  3.41130129e-16,
         1.00000000e+00,  1.57785406e-16],
       [-2.14996987e-16, -1.23208373e-16, -2.80230675e-16,
         3.31092525e-16,  1.00000000e+00]])

In [45]:
q,r = qr(mat)
q,r

(array([[-0.72084794, -0.05909149,  0.18692834, -0.01151615,  0.66468911],
        [ 0.13891681, -0.66034393,  0.6860316 ,  0.25432623, -0.09657552],
        [ 0.25768792, -0.3118446 , -0.52629815,  0.62512981,  0.41057626],
        [ 0.32113745, -0.45211425, -0.17888167, -0.73552576,  0.34563947],
        [ 0.53995189,  0.50872365,  0.43061589,  0.05831054,  0.5107074 ]]),
 array([[-3.37622931,  0.9423593 ,  1.23339202,  1.56764694,  3.38323251],
        [ 0.        , -3.55859615, -2.50570201, -4.09651524,  4.92739427],
        [ 0.        ,  0.        , -0.69005625, -1.11042029,  1.99482674],
        [ 0.        ,  0.        ,  0.        , -0.98133473,  0.75739107],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.81661404]]))

In [46]:
from numpy.linalg import det,eig,inv,qr,svd,solve,lstsq

In [47]:
arr = np.arange(1,10).reshape(3,3)
arr1 = np.arange(1,5).reshape(2,2)
arr ,arr1

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2],
        [3, 4]]))

In [144]:
det(arr) , det(arr1)

(-9.5161973539299405e-16, -2.0000000000000004)

In [48]:
# eig determines eigenvalues and eigenvectors of a square matrix => AX = lambdaX
eig(arr)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [49]:
svd(arr) # singular value decomposition into 3 matrices

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [52]:
np.trace(A) # sum of diagonal elements

-2